### ISSUE TITLE
Error with the configuration of a light dimmer

### ISSUE THREAD

**Issue by luca1982d** [Kane610/deconz#191]
MY CONFIGURATION
- Home Assistant 2021.12.6 on raspberry OS 
- Gateway ConBee II with firmware 26660700
- Deconz version 2.16.0
- Configured a light dimmer

On Home Assistant I see "Entity Unavailable"

![immagine](https://user-images.githubusercontent.com/71832621/147763260-5807f61d-9be2-4dee-a68a-d01033bd0b47.png)

ERROR ON HA
```
2021-12-30 15:54:21 ERROR (MainThread) [homeassistant.util.logging] Exception in async_update_connection_state when dispatching 'deconz-reachable-cdff0daea53abc75ef6f11b350a7fb3b': ()
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/components/deconz/deconz_device.py", line 85, in async_update_connection_state
    self.async_write_ha_state()
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity.py", line 505, in async_write_ha_state
    self._async_write_ha_state()
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/helpers/entity.py", line 540, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/components/light/__init__.py", line 906, in state_attributes
    data.update(self._light_internal_convert_color(color_mode))
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/components/light/__init__.py", line 833, in _light_internal_convert_color
    if color_mode == COLOR_MODE_HS and self.hs_color:
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/components/deconz/light.py", line 186, in hs_color
    return (self._device.hue / 65535 * 360, self._device.saturation / 255 * 100)
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'
```

[logerror.txt](https://github.com/Kane610/deconz/files/7793489/logerror.txt)

**Comment by Kane610** [comment]
Thanks for reporting! This is a device which reports color mode HS but does not report the hue and sat values, this is a Deconz bug.

An upstream report can be found here https://github.com/dresden-elektronik/deconz-rest-plugin/issues/5437
