### ISSUE TITLE
deCONZ has support for Philips Hue Tap switch, but deCONZ HA component not able to handle the sensor

### ISSUE THREAD

**Issue by mathos77** [Kane610/deconz#4]
As discussed over Discord already,

the HA component does not cope with Unknown sensor types, in this case the Philips Hue Tap switch.

A catch_all mechanism would be nice to cope with unknown sensors/lights/etc.
In this case, my priority is off course the Philips Hue Tap switch :)

Error messages during deCONZ component init:

```
2018-01-04 15:26:34 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up platform deconz
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/helpers/entity_component.py", line 171, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=self.hass.loop)
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.6/asyncio/futures.py", line 243, in result
    raise self._exception
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 180, in _step
    result = coro.send(None)
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 212, in coro
    res = func(*args, **kw)
  File "/usr/src/app/homeassistant/components/sensor/deconz.py", line 34, in async_setup_platform
    if sensor.type in DECONZ_SENSOR:
AttributeError: 'NoneType' object has no attribute 'type'
```

```
2018-01-04 15:26:34 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up platform deconz
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/helpers/entity_component.py", line 171, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=self.hass.loop)
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.6/asyncio/futures.py", line 243, in result
    raise self._exception
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 180, in _step
    result = coro.send(None)
  File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 212, in coro
    res = func(*args, **kw)
  File "/usr/src/app/homeassistant/components/binary_sensor/deconz.py", line 29, in async_setup_platform
    if sensor.type in DECONZ_BINARY_SENSOR:
AttributeError: 'NoneType' object has no attribute 'type'
```

And when tapping the TAP switch:

```
2018-01-04 15:28:52 DEBUG (MainThread) [pydeconz.websocket] Websocket data: b'\x81r{"e":"changed","id":"25","r":"sensors","state":{"buttonevent":34,"lastupdated":"2018-01-04T14:28:52"},"t":"event"}'
2018-01-04 15:28:52 ERROR (MainThread) [asyncio] Unhandled error in exception handler
context: {'exception': AttributeError("'NoneType' object has no attribute 'async_update'",)}
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 784, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/handles/stream.pyx", line 563, in uvloop.loop.UVStream._on_read
  File "/usr/local/lib/python3.6/site-packages/pydeconz/websocket.py", line 97, in data_received
    self.async_callback(payload)
  File "/usr/local/lib/python3.6/site-packages/pydeconz/__init__.py", line 139, in async_event_handler
    self.sensors[event['id']].async_update(event)
AttributeError: 'NoneType' object has no attribute 'async_update'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "uvloop/loop.pyx", line 2062, in uvloop.loop.Loop.call_exception_handler
  File "/usr/src/app/homeassistant/core.py", line 94, in async_loop_exception_handler
    _LOGGER.error("Error doing job: %s", context['message'], **kwargs)
KeyError: 'message'
```

The json of the switches (sensors) in deCONZ:

```
"24": {
        "config": {
            "on": true
        },
        "ep": 242,
        "etag": "fcdd940931497c1eaaea39876d6fd61a",
        "manufacturername": "Philips",
        "modelid": "ZGPSWITCH",
        "name": "moodswitch_bedroom",
        "state": {
            "buttonevent": 224,
            "lastupdated": "1970-01-01T00:00:00"
        },
        "type": "ZGPSwitch",
        "uniqueid": "00:00:00:00:00:47:9a:0b-f2"
    },
    "25": {
        "config": {
            "on": true
        },
        "ep": 242,
        "etag": "d154d65a8d5bbb6380b8ba414d180d1c",
        "manufacturername": "Philips",
        "modelid": "ZGPSWITCH",
        "name": "moodswitch_livingroom",
        "state": {
            "buttonevent": 34,
            "lastupdated": "2018-01-04T14:23:13"
        },
        "type": "ZGPSwitch",
        "uniqueid": "00:00:00:00:00:47:96:c9-f2"
    }
```

**Comment by Kane610** [comment]
I've created a PR now to fix this https://github.com/home-assistant/home-assistant/pull/11455
