### ISSUE TITLE
Legrand netatmo thermostat entitie doesn't work

### ISSUE THREAD

**Issue by Idaho947** [Kane610/deconz#528]
Hello,

I'm on the latest version on the deconz intergration and my server is on 2.23.2
On the on\off mode, everything is OK. When I pass it on wire pilot mode, the consumption is OK, but the thermostat is available.
![image](https://github.com/Kane610/deconz/assets/45599888/3fffec8e-d9a4-4d8b-855a-28fbf54d3ae0)

In the system journal I see that :
![image](https://github.com/Kane610/deconz/assets/45599888/779f514f-97a9-435a-b227-5e3f9af335f2)

`Logger: homeassistant
Source: components/deconz/climate.py:215
First occurred: 17:42:58 (4 occurrences)
Last logged: 17:50:10

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/pydeconz/gateway.py", line 210, in session_handler
    self.events.handler(self.websocket.data)
  File "/usr/local/lib/python3.11/site-packages/pydeconz/interfaces/events.py", line 66, in handler
    callback(event)
  File "/usr/local/lib/python3.11/site-packages/pydeconz/interfaces/api_handlers.py", line 184, in process_event
    self.process_item(event.id, event.changed_data)
  File "/usr/local/lib/python3.11/site-packages/pydeconz/interfaces/api_handlers.py", line 193, in process_item
    handler.process_item(id, raw)
  File "/usr/local/lib/python3.11/site-packages/pydeconz/interfaces/api_handlers.py", line 73, in process_item
    obj.update(raw)
  File "/usr/local/lib/python3.11/site-packages/pydeconz/models/api.py", line 78, in update
    callback()
  File "/usr/src/homeassistant/homeassistant/components/deconz/deconz_device.py", line 138, in async_update_callback
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 743, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 843, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 786, in _async_generate_attributes
    attr.update(self.state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 316, in state_attributes
    hass, self.current_temperature, temperature_unit, precision
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/deconz/climate.py", line 215, in current_temperature
    return self._device.scaled_temperature
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pydeconz/models/sensor/thermostat.py", line 387, in scaled_temperature
    return round(self.temperature / 100, 1)
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pydeconz/models/sensor/thermostat.py", line 382, in temperature
    return self.raw["state"]["temperature"]
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'temperature'
`
and
`Logger: homeassistant
Source: components/deconz/deconz_event.py:206
First occurred: 17:46:14 (4 occurrences)
Last logged: 18:01:14

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/pydeconz/gateway.py", line 210, in session_handler
    self.events.handler(self.websocket.data)
  File "/usr/local/lib/python3.11/site-packages/pydeconz/interfaces/events.py", line 66, in handler
    callback(event)
  File "/usr/local/lib/python3.11/site-packages/pydeconz/interfaces/api_handlers.py", line 184, in process_event
    self.process_item(event.id, event.changed_data)
  File "/usr/local/lib/python3.11/site-packages/pydeconz/interfaces/api_handlers.py", line 193, in process_item
    handler.process_item(id, raw)
  File "/usr/local/lib/python3.11/site-packages/pydeconz/interfaces/api_handlers.py", line 73, in process_item
    obj.update(raw)
  File "/usr/local/lib/python3.11/site-packages/pydeconz/models/api.py", line 78, in update
    callback()
  File "/usr/src/homeassistant/homeassistant/components/deconz/deconz_event.py", line 206, in async_update_callback
    or self._device.action not in SUPPORTED_DECONZ_ALARM_EVENTS
       ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pydeconz/models/sensor/ancillary_control.py", line 96, in action
    return AncillaryControlAction(self.raw["state"]["action"])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 712, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 1135, in __new__
    raise ve_exc
ValueError: 'already_disarmed' is not a valid AncillaryControlAction`

**Comment by Idaho947** [comment]
Any news about this issue ?

**Comment by Kane610** [comment]
Hello, this is the French special mode this one thermostat can be in right?

**Comment by Kane610** [comment]
Ok. As the situation is right now I will not myself add support for this other mode.  I find myself with very limited time on my home assistant integrations. Also this is a very niche device run by very few users in this context. Of course I will not say no to contributions putting the effort into supporting it.

Sorry

**Comment by Idaho947** [comment]
Ok thanks for your answer.
